docs: Convertidos documentos a código.
ispp-2324-ocial/KB pull request #13
Opened 2024-02-22 13:44 UTC by lDrakohh

PR de Juanjo para convertir los documentos asociados. 

**Aún están por teminar**, se añadirá comentario para cierre. Tiempo estimado unos 30-45 minutos.

2024-02-22 14:12 UTC, lDrakohh commented
Ya se puede revisar para cerrar. Se han creado dos carpetas dentro de doc, una para actas y otra para feedback

2024-02-22 14:36 UTC, ferferga requested changes
Habría que referenciar las imágenes correctamente como explico aquí:

https://github.com/ispp-2324-ocial/KB/pull/12#discussion_r1499339131

Etiqueto como blocked para que primero tengamos listo el repositorio con las imágenes

2024-02-24 13:52 UTC, ferferga commented
@lDrakohh Rebasa con main para corregir los conflictos porfa

2024-02-25 15:08 UTC, lDrakohh commented
Aviso cuando suba acta de la reunión de backend que estamos teniendo ahora mismo.

2024-02-25 15:41 UTC, lDrakohh commented
Ya se puede hacer merge @ferferga

2024-02-25 15:49 UTC, ferferga commented
@lDrakohh No lo has hecho con rebase

2024-02-27 18:01 UTC, ferferga approved these changes

2024-02-27 18:01 UTC, merged